### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/react-testing-library-course#1]
Show how to test a page

**Comment by liamse** [comment]
Can you explain a little more? what do you mean of "test a page"?

**Comment by kentcdodds** [comment]
It's similar to an E2E test (render the whole app), except you mock out http requests.

**Comment by pauldariye** [comment]
Hey, @kentcdodds listening to you on Youtube Live atm talking about TDD. I've used cypress.io for integration tests but I've also heard good things about intern

**Comment by kentcdodds** [comment]
I think you'll both love [the course](https://testingjavascript.com)!

**Comment by francodalessio** [comment]
Hi @kentcdodds ! I've just watched your video where you write the integration test. And then in the next video, you replace all the _getBy_ queries for _await findBy*_ queries. So my question is, if it's better to use just _findBy*_ queries, what's the use case for the _getBy*_ queries? Or why do they exist at all? Thanks!

**Comment by kentcdodds** [comment]
Great question @francodalessio! You can definitely use `find*` queries exclusively and you'll be fine. I'd say the only benefit to `get*` queries is not having to `await` whenever you're trying to retrieve elements. This argument is pretty weak though. I'm seriously considering recommending people use `find*` most of the time.
