### ISSUE TITLE
Should we use npm or yarn?

### ISSUE THREAD

**Issue by juliojguerra** [kentcdodds/react-testing-library-course#11]
It seems that we should use `npm` as there is no `yarn.lock` file in this repo. However, `npm install` didn't work for me so I couldn't run the tests.
After executing `yarn install` I could run `npm test [file_name]`

**Comment by kentcdodds** [comment]
Hi @juliojguerra!

I use `yarn` personally. It should work with `npm` though.

**Comment by kentcdodds** [comment]
It would be even better to watch the videos on TestingJavaScript.com and then try the same things you learn on your own project.

**Comment by juliojguerra** [comment]
Great suggestion, thanks @kentcdodds 🙏
