### ISSUE TITLE
Code for video doesn't match the code in the video

### ISSUE THREAD

**Issue by BernardoFBBraga** [kentcdodds/react-testing-library-course#12]
The video https://testingjavascript.com/lessons/react-test-prop-updates-with-react-testing-library
Links to the git file: https://github.com/kentcdodds/react-testing-library-course/blob/tjs/src/__tests__/prop-updates.js

Which is the code for the next video.

The difference is that in this stage you're using debug() to show the DOM.

Surely not a big issue, but I thought it'd be nice to give you a heads up. Thanks for the awesome content

**Comment by kentcdodds** [comment]
Thanks for this! I'll make sure that gets updated.
