### ISSUE TITLE
Disabling Animations Instead of Mocking

### ISSUE THREAD

**Issue by adam-beck** [kentcdodds/react-testing-library-course#16]
In the mock-component test you use the following snippet in order to essentially disable transitions.

```js
jest.mock('react-transition-group', () => {
  return {
    CSSTransition: props => (props.in ? props.children : null),
  }
})
```

However, there seems [to be a more idiomatic way](http://reactcommunity.org/react-transition-group/testing/)

```js
import { config } from 'react-transition-group

config.disabled = true
```

And I was curious if this was intentionally avoided? Or what are your thoughts on doing the 2nd method in tests instead?

**Comment by kentcdodds** [comment]
Thanks for that tip @adam-beck! I like your suggestion and that really is better! I'm not sure how long that feature has been around, but either way I guess I'll have to come up with another example of how to mock components in a future version of TestingJavaScript.com 😅

Thanks for mentioning this :)
