### ISSUE TITLE
Quick question: Not updated to use "screen"?

### ISSUE THREAD

**Issue by francodalessio** [kentcdodds/react-testing-library-course#17]
Hi @kentcdodds!

I'm watching the course and so far I'm loving it, thanks for it! 

I have a quick question. You mentioned in your ["Common mistakes with React Testing Library" post ](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library) that we should stop destructuring queries from _render_, and instead use _screen_.

Is it safe to assume then that everytime you destructure queries like this...

https://github.com/kentcdodds/react-testing-library-course/blob/88bbc8bc2465a436c8197717dfd673211bc36e90/src/__tests__/state.js#L6

...we should get rid of that and use _screen_?

Thanks!

**Comment by kentcdodds** [comment]
Correct. That's a pretty new feature and I'll be updating TestingJavaScript.com later this year (the update will be free to existing license holders) which will make this change :)
