### ISSUE TITLE
Running the application gives an exception

### ISSUE THREAD

**Issue by KevinBurton** [kentcdodds/react-testing-library-course#19]
I am running my application and getting an exception

```
$ kcd-scripts start
C:\Users\RKevi\source\repos\GreatState\GreatState\ClientApp\node_modules\kcd-scripts\dist\run-script.js:60
    throw new Error(`Unknown script "${script}".`);
    ^

Error: Unknown script "start".
    at spawnScript (C:\Users\RKevi\source\repos\GreatState\GreatState\ClientApp\node_modules\kcd-scripts\dist\run-script.js:60:11)
    at Object.<anonymous> (C:\Users\RKevi\source\repos\GreatState\GreatState\ClientApp\node_modules\kcd-scripts\dist\run-script.js:12:3)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (C:\Users\RKevi\source\repos\GreatState\GreatState\ClientApp\node_modules\kcd-scripts\dist\index.js:16:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
There is something missing from the configuration that makes the script available.

**Comment by kentcdodds** [comment]
Do you have a link to your project? You shouldn't be using kcd-scripts... Do you mean to use react-scripts?

This project uses kcd-scripts for development, but other than that it has nothing to do with kcd-scripts.

**Comment by KevinBurton** [comment]
Kent,

Thank you for your course and your help. I was trying to add testing to an
existing application built with CRA. The problem seems like kcd-scripts
uses a different version of Jest than react-scripts. So when I run it
unless I disable the check the different versions of Jest cause an
exception. I can run the application using 'react-scripts start' but cannot
without putting a recommended line in .env

SKIP_PREFLIGHT_CHECK=true

Kevin

**Comment by nickmccurdy** [comment]
Try the [Running Tests docs for create-react-app](https://create-react-app.dev/docs/running-tests/). Note that your `package.json` should have something like `react-scripts test`, not `kcd-scripts test`. The latter can probably be uninstalled.

**Comment by kentcdodds** [comment]
Oh, sorry, I was confused and thought this was a different repository 😅

This repo isn't intended to be actually run. All you need is to run the tests. Thanks!

**Comment by KevinBurton** [comment]
Kent,

If I remove kcd-scripts what am I giving up? It seems that kcd-scripts is
used throughout the course. It is in package.json for linting, building,
and validating. I is also used for configuring a package called husky,
eslint, and babel. Should this all be removed? Should it be replaced with
something?

Thank you.

Kevin

**Comment by nickmccurdy** [comment]
If you want to use create-react-app, it already has a Babel, ESLint, and Jest setup

**Comment by KevinBurton** [comment]
Nick,

That is what I am seeing. If I run 'react-scripts test' as part of the test
script for a CRA app it seems to no longer use jest.config.js. One evidence
that I am seeing is that even though I have the configuration in
jest.config.js like:

    collectCoverageFrom: [
        'src/*.jsx',
        'src/*.ts',
        'src/*.tsx',
        'src/{components,store}/*.js',
        'src/{components,store}/*.jsx',
        'src/{components,store}/*.ts',
        'src/{components,store}/*.tsx'
    ],

I am seeing coverage for files src/*.js for which I have not written tests
for and shouldn't need to write tests for.

Kevin

**Comment by nickmccurdy** [comment]
For create-react-app, that configuration needs to go in the `"jest"` field of `package.json`. `jest.config.js` is not supported.

[Documentation](https://create-react-app.dev/docs/running-tests/#configuration)
