### ISSUE TITLE
Linter complaining on course code

### ISSUE THREAD

**Issue by jacklaurencegaray** [kentcdodds/react-testing-library-course#20]
The `kcd-scripts` linter has these warnings:

`Use screen to query DOM elements, screen.getByText eslint(testing-library/prefer-screen-queries)`
`Use screen to query DOM elements screen.queryByRole eslint(testing-library/prefer-screen-queries)`

Also complains on the usage of `debug()` during on the course code.

It's difficult for people who are new to testing to discern screen, especially this happens in the course code where `screen` is not part of the topics discussed (not sure if it's part of the future topics as I'm still in the middle part of the videos).
It's also normal to use `debug()` while learning so I think it shouldn't warn.

**Comment by kentcdodds** [comment]
I'm going to be recording updates to TestingJavaScript.com in the next few months. If you want everything to work as it does in the videos, make sure to use the same versions as are in the videos. Otherwise, you'll need to research a bit to see what changed

**Comment by nickmccurdy** [comment]
You can read [screen's API documentation](https://testing-library.com/docs/dom-testing-library/api-queries#screen) or [not using screen](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen) until the courses are updated. As for `debug`, the default config only warns. You can still use it when learning or developing tests, it's just not recommended to keep it around in production test code.
