### ISSUE TITLE
Repository website link is broken

### ISSUE THREAD

**Issue by tpruisimao** [kentcdodds/react-testing-library-course#26]
Repo website link seems to be an unexisting route.

[testingjavascript.com/courses/test-react-components-with-jest-and-react-testing-library-0bbe87](Link)

![image](https://user-images.githubusercontent.com/89404667/133283507-1efdda5c-3fc7-4f3e-88b3-3aef6b220746.png)

![image](https://user-images.githubusercontent.com/89404667/133283707-67ecfcef-a2f2-484d-b765-f2857322252e.png)

**Comment by kentcdodds** [comment]
Fixed, thanks!

**Comment by tpruisimao** [comment]
Thank you for all these amazing courses.
